
export const rnCollectFilter = [
  'alignContent',
  'alignItems',
  'alignSelf',
  'aspectRatio',
  'borderBottomWidth',
  'borderLeftWidth',
  'borderRightWidth',
  'borderTopWidth',
  'borderEndWidth',
  'borderStartWidth',
  'borderWidth',
  'bottom',
  'direction',
  'display',
  'end',
  'start',
  'flex',//简写
  'flexDirection',
  'flexBasis',
  'flexGrow',
  'flexShrink',
  'flexWrap',
  'height',
  'justifyContent',
  'left',
  'margin',//简写
  'marginBottom',
  'marginHorizontal',
  'marginLeft',
  'marginRight',
  'marginTop',
  'marginVertical',
  'marginEnd',
  'marginStart',
  'maxHeight',
  'maxWidth',
  'minHeight',
  'minWidth',
  'padding',//简写
  'paddingBottom',
  'paddingHorizontal',
  'paddingLeft',
  'paddingRight',
  'paddingTop',
  'paddingVertical',
  'paddingEnd',
  'paddingStart',
  'position',
  'right',
  'top',
  'width',
  'zIndex',
  'shadowColor',
  'shadowOffset',
  'shadowOpacity',
  'shadowRadius',
  'decomposedMatrix',
  'transform',//简写
  'transformMatrix',
  'backfaceVisibility',
  'backgroundColor',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderColor',
  'borderRadius',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'opacity',
  'overflow',
  'resizeMode',
  'tintColor',
  'overlayColor',
  'borderBottomColor',
  'borderLeftColor',
  'borderRightColor',
  'borderStyle',
  'borderTopColor',
  'elevation',
  'color',
  'fontFamily',
  'fontSize',
  'fontStyle',
  'fontVariant',
  'textTransform',
  'fontWeight',
  'includeFontPadding',
  'lineHeight',
  'textAlign',
  'textDecorationLine',
  'textShadowColor',
  'textShadowOffset',
  'textShadowRadius',
  'textAlignVertical',
  'letterSpacing',
  'textDecorationColor',
  'textDecorationStyle',
  'writingDirection',
  'autoFocus',
  'keyboardType',
  'maxLength',
  'onChangeText',
  'borderBottomEndRadius',
  'borderBottomStartRadius',
  'borderEndColor',
  'borderStartColor',
  'borderTopEndRadius',
  'borderTopStartRadius',

  'font',//简写
  'border',//简写
  'border-left',//简写
  'border-right',//简写
  'border-top',//简写
  'border-bottom',//简写
  'background',//简写
  'boxShadow',//简写
  'textShadow',//简写
  'textDecoration',//简写
];

export const rnCollectFilterAbbrevia = [
  'flex',//简写
  'margin',//简写
  'padding',//简写
  'transform',//简写

  'font',//简写
  'border',//简写
  'border-left',//简写
  'border-right',//简写
  'border-top',//简写
  'border-bottom',//简写
  'background',//简写
  'boxShadow',//简写
  'textShadow',//简写
  'textDecoration',//简写
];